In [97]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 와우
와우


In [98]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [99]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [100]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [101]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [102]:
arVal[1][2]

3.14

In [103]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [104]:
arVal[0][2]

't'

In [105]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [106]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [107]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [108]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [109]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [110]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [111]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [112]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [113]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [114]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [115]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [116]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [117]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [118]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [119]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [120]:
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [121]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [122]:
pandas_series[0]

30

In [123]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [124]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [125]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [126]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [127]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [128]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [129]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [130]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [131]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [132]:
# column 삭제
del df['score']

In [133]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [134]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [135]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [136]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [137]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0  0.212922  0.821581 -0.101060  0.416967 -0.796007
1 -1.045524 -0.904782 -0.056535 -1.021196  0.253096
2 -1.636688 -2.507634  1.490146  0.129526  1.854869
3  1.249411 -1.374028 -0.437129  0.744393 -0.890296
4  0.767409 -0.213942 -0.673556 -0.879257  0.193189

In [138]:
# 최대값
df.max()

A    1.249411
B    0.821581
C    1.490146
D    0.744393
E    1.854869
dtype: float64

In [139]:
# 최소값
df.min()

A   -1.636688
B   -2.507634
C   -0.673556
D   -1.021196
E   -0.890296
dtype: float64

In [140]:
# 평균
df.mean()

A   -0.090494
B   -0.835761
C    0.044373
D   -0.121913
E    0.122970
dtype: float64

In [141]:
# 표준편차
df.std()

A    1.217189
B    1.247307
C    0.846885
D    0.788413
E    1.105957
dtype: float64

In [142]:
# 누적값
df.cumsum()

A         B         C         D         E
0  0.212922  0.821581 -0.101060  0.416967 -0.796007
1 -0.832602 -0.083200 -0.157595 -0.604228 -0.542911
2 -2.469290 -2.590834  1.332551 -0.474702  1.311958
3 -1.219879 -3.964862  0.895422  0.269691  0.421661
4 -0.452469 -4.178804  0.221866 -0.609566  0.614850

In [143]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.090494 -0.835761  0.044373 -0.121913  0.122970
std    1.217189  1.247307  0.846885  0.788413  1.105957
min   -1.636688 -2.507634 -0.673556 -1.021196 -0.890296
25%   -1.045524 -1.374028 -0.437129 -0.879257 -0.796007
50%    0.212922 -0.904782 -0.101060  0.129526  0.193189
75%    0.767409 -0.213942 -0.056535  0.416967  0.253096
max    1.249411  0.821581  1.490146  0.744393  1.854869

In [144]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  0.212922  0.821581 -0.101060  0.416967 -0.796007        X
1 -1.045524 -0.904782 -0.056535 -1.021196  0.253096        Y
2 -1.636688 -2.507634  1.490146  0.129526  1.854869        X
3  1.249411 -1.374028 -0.437129  0.744393 -0.890296        Y
4  0.767409 -0.213942 -0.673556 -0.879257  0.193189        Z

In [145]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.711883 -0.843026  0.694543  0.273247  0.529431
Y         0.101944 -1.139405 -0.246832 -0.138401 -0.318600
Z         0.767409 -0.213942 -0.673556 -0.879257  0.193189